### PR TITLE
Change API methods to post whenever necessary

### LINKED ISSUE #159: Use POST requests in API
API endpoints are all GET requests, we should be using POST to send data

### PR DESCRIPTION
**Pull request by gregory-latinier**
Fix #159

### CODE REVIEW

**Comment by gregory-latinier** [comment]
No, I've done the complete workflow in local before creating the PR

**Comment by jnordberg** [comment]
This is now a blocker for #129

**Comment by gregory-latinier** [comment]
I think you tried to use an existing email. Because of the apiCall wrapper the catch method wasn't working anymore so the error wasn't displayed.
May be this solves the issue. Could you try again please ?

**Comment by bonustrack** [comment]
Here is the error i got:
image
```
{"name":"faucet","hostname":"MacBook-Pro.local","pid":33162,"req_id":"dev-6595392562054517","ip":"::1","level":50,"err":{"message":"ResourceRequest timed out","name":"TimeoutError","stack":"TimeoutError: ResourceRequest timed out\n    at ResourceRequest._fireTimeout (/Users/fabien/WebstormProjects/steemit/faucet/node_modules/generic-pool/lib/ResourceRequest.js:62:17)\n    at Timeout.bound (/Users/fabien/WebstormProjects/steemit/faucet/node_modules/generic-pool/lib/ResourceRequest.js:8:15)\n    at ontimeout (timers.js:475:11)\n    at tryOnTimeout (timers.js:310:5)\n    at Timer.listOnTimeout (timers.js:270:5)"},"msg":"Unexpected API error","time":"2018-02-01T13:34:36.836Z","v":0}
```

**Comment by bonustrack** [comment]
It's working from time to time and error also happen in first step when choosing username:
image
I'm testing in localhost and I have very slow internet ATM that's probably what cause these timeout request on server side, there might be no real issue.

**Comment by jnordberg** [comment]
Tested in dev env and confirmed working

**Pull request merged**
