### PR TITLE
Remove the use of conveyor on the test net and configure it for mainnet use

### PR DESCRIPTION
**Pull request by gregory-latinier**

### CODE REVIEW

**Comment by gregory-latinier** [comment]
This PR is on hold until #125 can be fixed so this PR can be tested

**Comment by bonustrack** [comment]
I tried `signedCall` method in isolated code and got a different error, here is my code:
```
const steem = require('../lib');
const username = 'salut';
const wif = '****';
steem.api.setOptions({ url: 'https://conveyor.steemitdev.com' });

steem.api.signedCall('conveyor.is_email_registered', ['a@test.fr'], username, wif, (error, result) => {
  console.log('email', error, result);
});
```
Here is the error using `https://conveyor.steemitdev.com`:
image

**Comment by bonustrack** [comment]
@jnordberg any ideas? Do we still need to use `https://conveyor.steemitdev.com` endpoint?

**Comment by bonustrack** [comment]
Also does it require `@steemit/steem-js@0.7.0`?

**Comment by jnordberg** [comment]
@bonustrack We had an older version deployed, should work now. steem-js@0.7 should not be required

**Comment by bonustrack** [comment]
@jnordberg i just tested `@steemit/steem-js@0.6.10` and it give me the Checksum error aswell.

**Comment by jnordberg** [comment]
The snippet you pasted above runs fine for me with 0.6.10. Gives `email null false`

**Comment by bonustrack** [comment]
Ho yes sorry it's working for me now aswell with 0.6.1 I had an uncomplete key.

**Pull request merged**
