### PR TITLE
Add prettier and precommit

### LINKED ISSUE #153: set up prettier pre-commit hook
1. [ ] add prettier to dev deps
2. [ ] use steemit standard config: https://github.com/steemit/condenser/blob/58ef60baefbb0310b62f8d9e8da2a35a001cd9e1/.prettierrc
3. [ ] add precommit hook: https://github.com/steemit/condenser/pull/2105/commits/b3e67d4c0f970f8c5d6446b722f7200f37519781

### LINKED ISSUE #224: Use 4 spaces instead of 2 on the codebase

### PR DESCRIPTION
**Pull request by gregory-latinier**
Fix #153 
Fix #224
Instructions were given in this issue

### CODE REVIEW

**Comment by bnchdrff** [comment]
looks like we'll have to update this project's eslint to fit what prettier will write out, also

**Comment by gregory-latinier** [comment]
Indent is set to 2 for this project and to 4 in prettier
Do would you want to change to 4 and modify all files or set it to 2 in prettier ?

**Comment by bonustrack** [comment]
I think the plan is to use 4 spaces similar than `condenser` @bnchdrff can you confirm?

**Comment by bonustrack** [comment]
@gregory-latinier can you fix conflict?

**Comment by bonustrack** [comment]
When i start the faucet i got this error now:
image

Also, the file `makeConfig.js` and others files in `/webpack` folder should also have 4 spaces intend.

**Comment by gl2748** [comment]
@gregory-latinier  can you resolve conflicts and I will review...

**Pull request merged**
