### PR TITLE
prettier eslint armistice

### LINKED ISSUE #322: make peace between eslint and prettier
https://prettier.io/docs/en/eslint.html

### PR DESCRIPTION
**Pull request by bnchdrff**
closes #322 

adds [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier) to our eslint configuration so that it gets along with prettier.

this ensures that there aren't any races between prettier and eslint.

### CODE REVIEW

**Comment by gl2748** [comment]
And long may it last ... can we do away with prettier altogether - including `.prettier.rc` and make "yarn run lint" the pre-commit command? I say this because it looks like we're letting eslint handle formatting rules now...

**Comment by bnchdrff** [comment]
eslint --fix is much more heavyhanded & slower; the benefit of prettier is that it doesn't make any controversial decisions. i think it's useful to have both.

**Comment by gl2748** [comment]
In that case perhaps the move is to remove formatting rules from eslint? https://prettier.io/docs/en/comparison.html

**Comment by gl2748** [comment]
I would suggest a `.eslintrc` of simply:
```
{
  "extends": "react-app"
}
```

https://www.npmjs.com/package/eslint-config-react-app

**Comment by bnchdrff** [comment]
> In that case perhaps the move is to remove formatting rules from eslint? https://prettier.io/docs/en/comparison.html

that's what this PR does!

this project does require some `.eslint` trickery because it involves two different types of js code - client-side handled by webpack / transpilers and server-side that is not transpiled at all.

**Comment by bnchdrff** [comment]
we can simplify the eslint config when we split out the api server parts

**Pull request merged**
