### PR TITLE
Clarify the phone number in use message

### PR DESCRIPTION
**Pull request by plink01001**

### CODE REVIEW

**Comment by plink01001** [comment]
@pkattera can you please take a look at this?

**Comment by bonustrack** [comment]
The text changed is much longer than the previous one but still fit well IMO: image 
What do you think @pkattera ?

**Comment by pkattera** [comment]
I love providing a better explanation around this. A few minor update to this:

1. Update copy to make it a little shorter:

`This number is either already in use by an existing account, or linked to an account under review.`

2. Reduce the line-height of the error text copy to '1.3'. e.g.:

```
.Signup__container .Signup__form .has-error .ant-form-explain {
    text-align: left;
    line-height: 1.3;
}
```

Example screenshot, showing the message only taking up two lines on desktop.

screen shot 2018-02-26 at 1 01 43 pm

**Comment by plink01001** [comment]
@pkattera changes made

**Comment by pkattera** [comment]
@plink01001 Thanks! I approve.

**Pull request merged**
