### PR TITLE
220 validate email

### LINKED ISSUE #220: Add back email validation step
Having the email validation step part of the approval is bad ux. Users expect a validation email. It also creates some issues that are hard to address without redesigning the system, namely:

  * Users can signup with a typo in their address, verify their number and never receive the approval email.
  * Users can register multiple accounts using the same email and different phone numbers

### PR DESCRIPTION
**Pull request by gl2748**
Fixes #220 
Needs testing on dev/staging.

### CODE REVIEW

**Comment by gl2748** [comment]
To test locally apply this diff:
```
wget https://gist.githubusercontent.com/gl2748/f721d3ff5462152d6a8c4a79116d4e7e/raw/22f8929d9343d0b360f0f67c0b99a8aada782000/faucet_dev.diff  && git apply faucet_dev.diff
```

**Comment by gl2748** [comment]
220-faucet

**Comment by gl2748** [comment]
@jnordberg how would you like this step to be recorded in overseer?
@pkattera there are a couple of issues that I see.

- [ ]  'Almost There' step is missing a graphic.

- [ ]  Progress indicator should be updated to account for extra step.

**Comment by bnchdrff** [comment]
rather than requiring the diff for testing, what would it take to create an email service & then inject either sendgrid for prod or a logging dummy for testing?

**Comment by gl2748** [comment]
I agree that having a higher-order service for sendgrid would be a great idea. For local development it would be good if this also addressed the other things that need to be disabled for local dev to get to completion.

As I see it, to get to completion locally we would have to address:
- Find out why [querying local db for user data is returning null](https://gist.github.com/gl2748/f721d3ff5462152d6a8c4a79116d4e7e#file-faucet_dev-diff-L22) and either mock user data as I am currently doing, or get the local DB to behave as expected.
- [Turn off Recaptcha.](https://gist.github.com/gl2748/f721d3ff5462152d6a8c4a79116d4e7e#file-faucet_dev-diff-L69)
- [Turn off IP limiting.](https://gist.github.com/gl2748/f721d3ff5462152d6a8c4a79116d4e7e#file-faucet_dev-diff-L79)
- [Toggle off Sendgrid.](https://gist.github.com/gl2748/f721d3ff5462152d6a8c4a79116d4e7e#file-faucet_dev-diff-L37-L43)

I am not sure doing this is within the current scope of this work however. If we add an issue

**Comment by gl2748** [comment]
Ben suggests a service wrapper. Including a final step that tests the blockchain step.

One suggestion is that if the username / phone etc follows a certain pattern. E.g. `u: test-foobar`

**Comment by pkattera** [comment]
– Graphics
In the 'Almost there' step, let's use the exact same graphic from the email step.

- Progress indicators
Let's just remove the progress indicator on the 'Almost there' step.

- On the phone number screen
The 'Go back' option, currently takes people back to enter email step. In most cases, I doubt the user wants to edit their email address after confirming it. It may cause some users to press it by mistake and then have to reconfirm the same email address. I say, let's remove the 'Go back' link and if someone wants to use a different email address after confirming it, they can just start a new sign up.

**Comment by gl2748** [comment]
@pkattera sounds good I will work on that today.

I have been taking a closer look at some of the things that need to be stubbed out locally, this information might be useful for future work.

Locally the steem js api call:
https://github.com/steemit/faucet/blob/6ab364f1e2272ec9792334c008d55da7903e72b1/routes/api.js#L158-L164
Causes this error:
```
{"name":"faucet","hostname":"mimi","pid":26382,"req_id":"dev-5606985698537447","ip":"::1","level":50,"err":{"message":"Unauthorized","name":"RPCError","stack":"RPCError: Unauthorized\n    at new RPCError (/home/iain/faucet/node_modules/@steemit/steem-js/lib/api/transports/http.js:39:106)\n    at /home/iain/faucet/node_modules/@steemit/steem-js/lib/api/transports/http.js:74:13\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)","code":400},"msg":"Unexpected API error","time":"2018-03-14T19:27:48.823Z","v":0}
```

**Comment by gl2748** [comment]
final

**Comment by gl2748** [comment]
diff for local dev:
```
diff --git a/db/config/config.json b/db/config/config.json
index f70f9c9..103de6c 100644
--- a/db/config/config.json
+++ b/db/config/config.json
@@ -3,7 +3,7 @@
     "use_env_variable": "DATABASE_URL",
     "operatorsAliases": false,
     "dialectOptions": {
-      "ssl": true
+      "ssl": false
     }
   },
   "staging": {
diff --git a/routes/api.js b/routes/api.js
index bc04bc0..f0898fd 100644
--- a/routes/api.js
+++ b/routes/api.js
@@ -171,6 +171,8 @@ const sendConfirmationEmail = async (req, res) => {
     email: req.body.email,
   }, process.env.JWT_SECRET, { expiresIn: '1d' });
 
+  const link = `${req.protocol}://${req.get('host')}/confirm-email?token=${mailToken}`;
+
   // If the user has not made a prior attempt, send an email.
   if (!usersLastAttempt) sendEmail(req, mailToken);
 
@@ -190,7 +192,7 @@ const sendConfirmationEmail = async (req, res) => {
 
   // Return success back to the client.
   // TODO: find out what token is used for.
-  res.json({ success: true, token });
+  res.json({ success: true, token, link });
 };
 
 /**
@@ -204,7 +206,7 @@ const sendConfirmationEmail = async (req, res) => {
 router.post('/request_email', apiMiddleware(async (req, res) => {
   const location = req.geoip.get(req.ip);
 
-  let skipRecaptcha = false;
+  let skipRecaptcha = true;
   if (location && location.country && location.country.iso_code === 'CN') {
     skipRecaptcha = true;
   }
@@ -221,7 +223,7 @@ router.post('/request_email', apiMiddleware(async (req, res) => {
     throw new ApiError({ type: 'error_api_domain_blacklisted', field: 'email' });
   }
 
-  await actionLimit(req.ip);
+  //await actionLimit(req.ip);
 
   await req.db.actions.create({
     action: 'request_email',
@@ -239,6 +241,7 @@ router.post('/request_email', apiMiddleware(async (req, res) => {
     throw new ApiError({ type: 'error_api_email_used', field: 'email' });
   }
 
+  /*
   const emailRegistered = await steem.api.signedCallAsync(
     'conveyor.is_email_registered', [req.body.email],
     conveyorAccount, conveyorKey,
@@ -246,6 +249,7 @@ router.post('/request_email', apiMiddleware(async (req, res) => {
   if (emailRegistered) {
     throw new ApiError({ type: 'error_api_email_used', field: 'email' });
   }
+  */
 
   if (!skipRecaptcha) {
     try {
diff --git a/src/components/Form/Signup/Email.js b/src/components/Form/Signup/Email.js
index b56f8b8..9cefd7d 100644
--- a/src/components/Form/Signup/Email.js
+++ b/src/components/Form/Signup/Email.js
@@ -77,6 +77,8 @@ class Email extends React.Component {
           recaptcha: window.grecaptcha.getResponse(),
         })
           .then((data) => {
+            console.log('DATA!', data)
+            console.log('LINK!', data.link)
             this.setState({ submitting: false });
             if (data.success) {
               if (onSubmit) {
```

**Comment by jnordberg** [comment]
Tested on dev, flow works as expected. @pkattera is the copy ok?

screen shot 2018-03-19 at 16 44 21
screen shot 2018-03-19 at 16 44 13
screen shot 2018-03-19 at 16 44 50

**Comment by pkattera** [comment]
Some minor tweaks:

1. Please replace the heading 'Almost there' with 'Check your email'. 
This places the key action that we want users to do upfront, in an easily scannable fashion.

2. In the email, place a new line after 'Cheers', so it reads

Cheers
Your friends at Steemit

3. On the 'Thank you' screen', please change the heading to 'Thanks [@username]'
We know that some users are forgetting the user name they initially selected, so let's remind and reinforce their selected username.

**Comment by gl2748** [comment]
@pkattera @jnordberg. I will do that now  - one thing I would say is that  'Complete Signup'  takes the user to the SMS confirmation step ... not sure if we want to say something different like 'Continue'...

Also some things to consider down the line:
- Sendgrid supports html/css for emails - something to keep in mind, might be nice to style the emails.

**Comment by jnordberg** [comment]
Agreed, continue signup sounds better than complete when there are more steps after

**Comment by gl2748** [comment]
@pkattera @jnordberg 
Ok So i have done all of that:

## CHECK YOUR EMAIL
screenshot from 2018-03-19 12-10-16

## EMAIL
screenshot from 2018-03-19 12-19-46
**NOTE** I also added the username to the confirmation email. I understand this is possibly contentious and am happy to walk it back, on the plus side it does give the user a permament record of their account username, albeit for an in-progress account creation:

## EMAIL CONFIRMED
screenshot from 2018-03-19 12-22-38

**Comment by gl2748** [comment]
hey @pkattera ok, i removed the username from the email and added the '@' symbol to the success screen.

**Comment by jnordberg** [comment]
👍  lgtm

**Pull request merged**
